services:
  web1:
    build: .
    command: python manage.py runserver 172.19.0.3:80
    restart: always
    volumes:
      - .:/app
    networks:
      mreza:
        ipv4_address: 172.19.0.3
    extra_hosts:
    - "host.docker.internal:172.17.0.1"   
  web2:
    build: .
    command: python manage.py runserver 172.19.0.4:80
    restart: always
    volumes:
      - .:/app
    networks:
      mreza:
        ipv4_address: 172.19.0.4
    extra_hosts:
    - "host.docker.internal:172.17.0.1"
  web3:
    build: .
    command: python manage.py runserver 172.19.0.6:80
    restart: always
    volumes:
      - .:/app
    networks:
      mreza:
        ipv4_address: 172.19.0.6
    extra_hosts:
    - "host.docker.internal:172.17.0.1"
  loadBalancer:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./conf:/etc/nginx/conf.d:ro
    networks:
      mreza:
        ipv4_address: 172.19.0.5

networks:
  mreza:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
