version: '4'

services:
  web1:
    build: .
    command: python manage.py runserver --insecure 172.19.0.3:80
    restart: always
    volumes:
      - .:/app
      - ./static:/app/static  # Mount a volume for storing static files
      - ./media:/app/media:rw # Mount a volume for storing media files
    networks:
      mreza:
        ipv4_address: 172.19.0.3
    depends_on:
      - postgres
  web2:
    build: .
    command: python manage.py runserver --insecure 172.19.0.4:80
    restart: always
    volumes:
      - .:/app
      - ./static:/app/static  # Mount a volume for storing static files
      - ./media:/app/media:rw  # Mount a volume for storing media files
    networks:
      mreza:
        ipv4_address: 172.19.0.4
    depends_on:
      - postgres
  web3:
    build: .
    command: python manage.py runserver --insecure 172.19.0.6:80
    restart: always
    volumes:
      - .:/app
      - ./static:/app/static  # Mount a volume for storing static files
      - ./media:/app/media:rw  # Mount a volume for storing media files
    networks:
      mreza:
        ipv4_address: 172.19.0.6
    depends_on:
      - postgres

  loadBalancer:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./conf:/etc/nginx/conf.d:ro
    networks:
      mreza:
        ipv4_address: 172.19.0.5
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgAdmin_Pa55w0rd
    volumes:
      - ./pgadmin_data:/app/pgadmin
    networks:
      mreza:
        ipv4_address: 172.19.0.7
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    user: root
    volumes:
      - ./postgres_data:/app/postgresql/data
    networks:
      mreza:
        ipv4_address: 172.19.0.8

networks:
  mreza:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
