# Generated by Django 5.0.1 on 2024-04-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('file', models.FileField(upload_to='upload/')),
                ('studentFirstName', models.CharField(max_length=50, null=True)),
                ('studentLastName', models.CharField(max_length=50, null=True)),
                ('thesisDefenseDate', models.DateField(null=True)),
                ('thesisType', models.CharField(choices=[('dipl.', 'Diplomski rad'), ('mag.', 'Magistarski rad'), ('dr.', 'Doktorski rad')], max_length=30, null=True)),
                ('thesisDefensePlace', models.CharField(max_length=100, null=True)),
                ('wordCount', models.IntegerField(null=True)),
                ('fileSize', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
