# Generated by Django 4.2.4 on 2024-01-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfile',
            name='file',
            field=models.FileField(upload_to='student_files/files/'),
        ),
    ]
