# Generated by Django 4.2.13 on 2024-06-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfile',
            name='OriginalFileName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentfile',
            name='UidFileName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
