# Generated by Django 4.2.13 on 2024-06-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_files', '0002_studentfile_originalfilename_studentfile_uidfilename'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfile',
            name='Classification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
